-- MySQL Script generated by MySQL Workbench
-- Wed Jun 29 22:45:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_factura
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_factura
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_factura` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `db_factura` ;

-- -----------------------------------------------------
-- Table `db_factura`.`tbl_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_factura`.`tbl_empresa` (
  `empresa_id` INT NOT NULL AUTO_INCREMENT,
  `empresa_nombre` VARCHAR(200) NOT NULL,
  `empresa_direccion` LONGTEXT NULL,
  `empresa_ruc` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`empresa_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_factura`.`tbl_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_factura`.`tbl_factura` (
  `factura_id` INT NOT NULL AUTO_INCREMENT,
  `factura_nro` VARCHAR(100) NOT NULL,
  `factura_fecha_emision` DATE NOT NULL,
  `factura_tipo_moneda` VARCHAR(20) NOT NULL,
  `factura_valor_venta` DOUBLE NOT NULL,
  `factura_importe_total` DOUBLE NOT NULL,
  `emisor_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`factura_id`),
  CONSTRAINT `fk_tbl_factura_tbl_empresa1`
    FOREIGN KEY (`emisor_id`)
    REFERENCES `db_factura`.`tbl_empresa` (`empresa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_factura_tbl_empresa2`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `db_factura`.`tbl_empresa` (`empresa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_factura`.`tbl_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_factura`.`tbl_producto` (
  `producto_id` INT NOT NULL AUTO_INCREMENT,
  `producto_codigo` VARCHAR(100) NOT NULL,
  `producto_descripcion` VARCHAR(255) NOT NULL,
  `producto_unidad_medida` VARCHAR(100) NULL,
  PRIMARY KEY (`producto_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_factura`.`tbl_factura_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_factura`.`tbl_factura_detalle` (
  `facdet_id` INT NOT NULL AUTO_INCREMENT,
  `factura_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  `facdet_cantidad` DOUBLE NOT NULL,
  `facdet_valor_unitario` DOUBLE NULL,
  PRIMARY KEY (`facdet_id`),
  CONSTRAINT `fk_tbl_factura_detalle_tbl_producto`
    FOREIGN KEY (`producto_id`)
    REFERENCES `db_factura`.`tbl_producto` (`producto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_factura_detalle_tbl_factura1`
    FOREIGN KEY (`factura_id`)
    REFERENCES `db_factura`.`tbl_factura` (`factura_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_factura`.`tbl_impuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_factura`.`tbl_impuesto` (
  `impuesto_id` INT NOT NULL AUTO_INCREMENT,
  `impuesto_nombre` VARCHAR(45) NOT NULL,
  `impuesto_porcentaje` DOUBLE NULL,
  `impuesto_monto` DOUBLE NULL,
  PRIMARY KEY (`impuesto_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_factura`.`tbl_factura_impuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_factura`.`tbl_factura_impuesto` (
  `facimp_id` INT NOT NULL AUTO_INCREMENT,
  `facimp_monto` DOUBLE NOT NULL,
  `factura_id` INT NOT NULL,
  `impuesto_id` INT NOT NULL,
  PRIMARY KEY (`facimp_id`),
  CONSTRAINT `fk_factura_impuesto_tbl_factura1`
    FOREIGN KEY (`factura_id`)
    REFERENCES `db_factura`.`tbl_factura` (`factura_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_impuesto_tbl_impuesto1`
    FOREIGN KEY (`impuesto_id`)
    REFERENCES `db_factura`.`tbl_impuesto` (`impuesto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
