# Generated by Django 3.2 on 2022-08-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_nombre', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
            options={
                'db_table': 'tbl_categoria',
            },
        ),
    ]
