# Generated by Django 3.2 on 2022-08-20 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_curso_miembro'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='categoria_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to='api.categoria', verbose_name='Categoria'),
        ),
    ]
