# Generated by Django 3.2 on 2022-08-23 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220819_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='curso_refid',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='curso',
            name='categoria_id',
            field=models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.RESTRICT, related_name='Cursos', to='api.categoria', verbose_name='Categoria'),
        ),
    ]
