# Generated by Django 3.2 on 2022-07-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_nom', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'db_table': 'tbl_categoria',
            },
        ),
        migrations.AlterField(
            model_name='mesa',
            name='mesa_cap',
            field=models.IntegerField(default=0, verbose_name='Capacidad'),
        ),
    ]
